name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  REGISTRY: git.noel.sh
  DOCS_IMAGE_NAME: codespace/codewire.sh
  DEPLOY_CONTEXT: app
  DOCS_NAMESPACE: codewire-prod

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: go test ./internal/... ./tests/... -timeout 120s -count=1

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: go build -o cw ./cmd/cw

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: go vet ./...

  build-docs:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.meta.outputs.tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Set image tag
        id: meta
        run: |
          if [ "${{ gitea.event_name }}" = "pull_request" ]; then
            echo "tag=pr-${{ gitea.event.pull_request.number }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ gitea.sha }}" >> $GITHUB_OUTPUT
          fi

      - name: Authenticate to Infisical
        run: |
          RESPONSE=$(curl -s -X POST "${INFISICAL_API_URL}/v1/auth/oidc-auth/login" \
            -H "Content-Type: application/json" \
            -d "{\"identityId\": \"${INFISICAL_IDENTITY_ID}\", \"jwt\": \"$(cat ${INFISICAL_SA_TOKEN_PATH})\"}")
          ACCESS_TOKEN=$(echo "$RESPONSE" | jq -r '.accessToken')
          if [ "$ACCESS_TOKEN" = "null" ] || [ -z "$ACCESS_TOKEN" ]; then
            echo "Failed to authenticate"; echo "$RESPONSE"; exit 1
          fi
          echo "INFISICAL_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV

      - name: Login to Gitea Registry
        run: |
          REGISTRY_TOKEN=$(curl -s "${INFISICAL_API_URL}/v3/secrets/raw/GITEA_REGISTRY_TOKEN?workspaceSlug=shared&environment=prod&secretPath=/ci" \
            -H "Authorization: Bearer ${INFISICAL_TOKEN}" | jq -r '.secret.secretValue')
          echo "$REGISTRY_TOKEN" | docker login $REGISTRY -u ci --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker

      - name: Build and push docs image
        if: gitea.event_name != 'pull_request'
        uses: docker/build-push-action@v5
        with:
          context: docs/
          file: docs/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.DOCS_IMAGE_NAME }}:${{ steps.meta.outputs.tag }},${{ env.REGISTRY }}/${{ env.DOCS_IMAGE_NAME }}:latest

  deploy-docs:
    runs-on: ubuntu-latest
    needs: [build-docs, test]
    if: gitea.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Infisical
        run: |
          RESPONSE=$(curl -s -X POST "${INFISICAL_API_URL}/v1/auth/oidc-auth/login" \
            -H "Content-Type: application/json" \
            -d "{\"identityId\": \"${INFISICAL_IDENTITY_ID}\", \"jwt\": \"$(cat ${INFISICAL_SA_TOKEN_PATH})\"}")
          ACCESS_TOKEN=$(echo "$RESPONSE" | jq -r '.accessToken')
          echo "INFISICAL_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV

      - name: Setup kubeconfig
        run: |
          mkdir -p ~/.kube
          KUBECONFIG_CONTENT=$(curl -s "${INFISICAL_API_URL}/v3/secrets/raw/KUBECONFIG_CI?workspaceSlug=system&environment=prod&secretPath=/ci" \
            -H "Authorization: Bearer ${INFISICAL_TOKEN}" | jq -r '.secret.secretValue')
          if [ -z "$KUBECONFIG_CONTENT" ] || [ "$KUBECONFIG_CONTENT" = "null" ]; then
            echo "Error: Could not retrieve kubeconfig from Infisical"; exit 1
          fi
          echo "$KUBECONFIG_CONTENT" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Update manifests with image tag
        run: |
          sed -i "s|IMAGE_TAG|${{ needs.build-docs.outputs.image_tag }}|g" k8s/docs/*.yaml
          sed -i "s|REGISTRY_URL|$REGISTRY|g" k8s/docs/*.yaml
          sed -i "s|IMAGE_NAME|$DOCS_IMAGE_NAME|g" k8s/docs/*.yaml

      - name: Deploy docs to cluster
        run: |
          kubectl --context=$DEPLOY_CONTEXT apply -f k8s/docs/ -n $DOCS_NAMESPACE
          kubectl --context=$DEPLOY_CONTEXT rollout status deployment/codewire-docs -n $DOCS_NAMESPACE --timeout=300s

      - name: Show deployment status
        run: |
          echo "=== Pods ==="
          kubectl --context=$DEPLOY_CONTEXT get pods -n $DOCS_NAMESPACE
          echo "=== Ingress ==="
          kubectl --context=$DEPLOY_CONTEXT get ingress -n $DOCS_NAMESPACE
