name: Deploy

on:
  push:
    tags: ['v*']

jobs:
  deploy:
    name: Build Images & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codewire
        uses: actions/checkout@v4

      - name: Checkout infra
        uses: actions/checkout@v4
        with:
          repository: codespace/infra
          token: ${{ secrets.GITEA_PAT }}
          path: infra
          server-url: "https://${{ secrets.GITEA_HOST }}"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build cw binary for demo image
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o demo/cw ./cmd/cw

      - name: Authenticate to Infisical
        run: |
          RESPONSE=$(curl -s -X POST "${{ secrets.INFISICAL_HOST }}/v1/auth/oidc-auth/login" \
            -H "Content-Type: application/json" \
            -d "{\"identityId\":\"${{ secrets.INFISICAL_IDENTITY_ID }}\",\"jwt\":\"$(cat ${{ secrets.INFISICAL_SA_TOKEN_PATH }})\"}")
          ACCESS_TOKEN=$(echo "$RESPONSE" | jq -r '.accessToken')
          [ "$ACCESS_TOKEN" = "null" ] && { echo "$RESPONSE"; exit 1; }
          echo "INFISICAL_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV

      - name: Login to registry
        run: |
          TOKEN=$(curl -s "${{ secrets.INFISICAL_HOST }}/v3/secrets/raw/GITEA_REGISTRY_TOKEN?workspaceSlug=codespace&environment=prod&secretPath=/ci" \
            -H "Authorization: Bearer $INFISICAL_TOKEN" | jq -r '.secret.secretValue')
          echo "$TOKEN" | docker login ${{ secrets.REGISTRY_HOST }} -u ci --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker

      - name: Build and push docs image
        uses: docker/build-push-action@v5
        with:
          context: docs
          push: true
          tags: |
            ${{ secrets.REGISTRY_HOST }}/codespace/codewire.sh:${{ github.ref_name }}
            ${{ secrets.REGISTRY_HOST }}/codespace/codewire.sh:latest

      - name: Build and push demo image
        uses: docker/build-push-action@v5
        with:
          context: demo
          push: true
          tags: |
            ${{ secrets.REGISTRY_HOST }}/codespace/codewire-demo:${{ github.ref_name }}
            ${{ secrets.REGISTRY_HOST }}/codespace/codewire-demo:latest

      - name: Build and push broker image
        uses: docker/build-push-action@v5
        with:
          context: demo/broker
          push: true
          tags: |
            ${{ secrets.REGISTRY_HOST }}/codespace/codewire-demo-broker:${{ github.ref_name }}
            ${{ secrets.REGISTRY_HOST }}/codespace/codewire-demo-broker:latest

      - name: Deploy via Terraform
        run: |
          cd infra
          ./scripts/atmos-run terraform apply codewire -s ${{ secrets.APP_ATMOS_STACK }} \
            -- -auto-approve \
               -var="docs_image_tag=${{ github.ref_name }}" \
               -var="demo_image_tag=${{ github.ref_name }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          KUBECONFIG: infra/kubeconfig-app.yaml
